#!/usr/bin/env bash
if [ builder/Tasks.java -nt builder/Tasks.class ] || [ builder/BuildUtils.java -nt builder/BuildUtils.class ]; then
    javac -cp builder/commons-compress-1.27.1.jar:builder/commons-io-2.16.1.jar:builder/commons-lang3-3.18.0.jar builder/Tasks.java builder/BuildUtils.java
fi
java -cp ".:builder/commons-compress-1.27.1.jar:builder/commons-io-2.16.1.jar:builder/commons-lang3-3.18.0.jar" -Dsun.security.pkcs11.enable-solaris=false builder.Tasks "$@"
