;; Golden scenario: the agenda listing and refresh.
(deftemplate n (slot v))
(defrule high (declare (salience 200)) (n (v ?v)) => (printout t "high " ?v crlf))
(defrule low (n (v ?v)) => (printout t "low " ?v crlf))
(assert (n (v 1)))
(assert (n (v 2)))
(agenda)
(fire 1)
(agenda)
(fire)
(agenda)
(refresh low)
(agenda)
(fire)
(refresh low)
(retract 2)
(agenda)
