;; Golden scenario: deffunction bodies with several expressions, loops inside them,
;; return, recursion and calls from rule actions.
(deffunction sum-list (?list)
  (bind ?sum 0)
  (foreach ?v ?list (bind ?sum (+ ?sum ?v)))
  ?sum)
(printout t "sum-list " (sum-list (create$ 1 2 3)) crlf)
(deffunction size (?a ?b)
  (bind ?c (+ ?a ?b))
  (if (> ?c 10) then (return "big"))
  "small")
(printout t "size " (size 1 2) " " (size 8 9) crlf)
(deffunction factorial (?n)
  (if (<= ?n 1) then 1 else (* ?n (factorial (- ?n 1)))))
(printout t "factorial " (factorial 5) crlf)
(deffunction count-to (?n)
  (bind ?i 0)
  (loop-for-count (?k 1 ?n) (bind ?i (+ ?i ?k)))
  ?i)
(printout t "count-to " (count-to 4) crlf)
(deffunction len (?list) (length$ ?list))
(printout t "len " (len (create$ a b)) crlf)
(deffunction greet (?name) (printout t "hello " ?name crlf) (str-cat "greeted " ?name))
(printout t (greet "world") crlf)
(deftemplate n (slot v))
(defrule use-functions
  (n (v ?v))
=>
  (printout t "f(" ?v ")=" (factorial ?v) " " (size ?v ?v) crlf))
(assert (n (v 3)))
(assert (n (v 6)))
