;; Golden scenario: subseq$, replace$, delete-member$, gensym, setgen, seed and random.
(bind ?l (create$ a b c d e))
(printout t (subseq$ ?l 2 4) crlf)
(printout t (subseq$ ?l 4 9) crlf)
(printout t (replace$ ?l 2 3 x) crlf)
(printout t (replace$ ?l 2 3 (create$ x y z)) crlf)
(printout t (delete-member$ ?l b d) crlf)
(printout t (delete-member$ (create$ 1 2 1 3) 1) crlf)
(printout t (gensym) " " (gensym) " " (gensym*) crlf)
(setgen 100)
(printout t (gensym) crlf)
(seed 7)
(bind ?r (random 1 6))
(printout t (integerp ?r) " " (>= ?r 1) " " (<= ?r 6) crlf)
(printout t (< (random) 1) crlf)
(printout t (numberp (time)) crlf)
