;; Golden scenario: file routers. A file is written with printout and format, then read back
;; with readline and read.
(open "target/routers_scenario.txt" out "w")
(printout out "first line" crlf)
(format out "%s %d%n" "second" 2)
(printout out "3.5 rest of line" crlf)
(close out)
(open "target/routers_scenario.txt" in "r")
(printout t "1: " (readline in) crlf)
(printout t "2: " (readline in) crlf)
(bind ?n (read in))
(printout t "3: " ?n " " (numberp ?n) " " (+ ?n 1) crlf)
(printout t "4: " (readline in) crlf)
(close in)
(open "target/routers_scenario.txt" out "a")
(printout out "appended" crlf)
(close)
(open "target/routers_scenario.txt" in)
(bind ?count 0)
(while (neq (readline in) "EOF") do (bind ?count (+ ?count 1)))
(printout t "lines: " ?count crlf)
(close in)
